### ISSUE TITLE
Responsive issue in book view page 

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#10]
![Screenshot from 2021-05-17 10-27-03](https://user-images.githubusercontent.com/70310447/118434298-72db8380-b6fa-11eb-8e8a-139f321d372e.png)

Refer this screenshot:

1. The book title is jumbed to bottom 
2. rate button is compressed 
3. Make these issues better

**Comment by AmshenShanu07** [comment]
1. fixed the title jumping down problem
2. fixed rate button compression problem
