### ISSUE TITLE
font , line issue in book view

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#11]
![Screenshot from 2021-05-17 10-30-55](https://user-images.githubusercontent.com/70310447/118434654-09a84000-b6fb-11eb-8939-85c8144d9a87.png)

Refer the Screenshot:

1. I think is better increase the font size of description little bit
2. Change font of rating line to montserrat
3. give cursor pointer to all buttons incuding like button
4. Look at the 2 lines above and below of reivew heading::::::::::::::::::::::::::::::::::::::::::::::::::::
5. it is not properly aligned """"""""""""""""""""""""
6. letf side has some margin but the right hadn't      make it better like the comments border line(its perfect)

**Comment by AmshenShanu07** [comment]
1. increased the font size under 768px and 500px
2. Changed font of rating line to montserrat
3. Made cursor pointer to all buttons 
4. made the hr aligned and both side with same spacing
