### ISSUE TITLE
add book issue

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#21]
![Screenshot from 2021-05-17 22-46-32](https://user-images.githubusercontent.com/70310447/118530158-f7152180-b761-11eb-9936-e3c6c3786d1e.png)

There is no heading (ADD BOOKS) and also there is no upload button

Add a text like add cover photo in coverphoto input becuase it will make user better user experienxce

**Comment by rishadpt** [comment]
issue fixed
