### ISSUE TITLE
add books responsive issues

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#22]
![Screenshot from 2021-05-17 22-47-14](https://user-images.githubusercontent.com/70310447/118530524-61c65d00-b762-11eb-84df-a9b13ccd3cc3.png)

1. Reduce the padding of the container because the space in textfield is not enough
2. add book alignment isn't correct
3. Make description to multline type because it may have more contents
4. mobile design or tablet design we only need below 768px if maximum 900px

**Comment by rishadpt** [comment]
issue fixed

**Comment by rishadpt** [comment]
issue fixed
