### ISSUE TITLE
issue in footer

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#23]
![Screenshot from 2021-05-18 13-17-12](https://user-images.githubusercontent.com/70310447/118612570-87dc1380-b7db-11eb-8118-0f65ea3ab352.png)

Need to align footer alwaly at the end give min-width:100vh for your add book container

**NB
The Min width is not media queries I mean min-width in style of container**

**Comment by rishadpt** [comment]
pull the lastest commits its fixed already
