### ISSUE TITLE
text alignment issue new

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#25]
![Screenshot from 2021-05-18 13-43-48](https://user-images.githubusercontent.com/70310447/118616226-21f18b00-b7df-11eb-9e61-e3d15e1020f2.png)

1. padding left of o the text field is high reduce it
2. only need a little padding 
3. text inside the add cover photo is not able to see 
4. give some more font weight to that font and also align it vertcally center inside that image div
5. reduce the font size of textfield little bit

**Comment by rishadpt** [comment]
issue already fixed
