### ISSUE TITLE
Filter button issue in header

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#4]
![Screenshot from 2021-05-16 20-10-15](https://user-images.githubusercontent.com/70310447/118401291-c1e5d200-b682-11eb-84cb-4d7c4cc35fa7.png)

1. Give cursor pointer to filter button
2. make filter better 
3. reduce the font size little bit
4. Increase font weight little bit
5. also consider the filter icon
6. only border radius needed in start of the button (left top and left bottom)
7. LOOK AT THE TITLE SPELLING MISTAKE     replace PICBOOK to PICKBOOK
8. Rename the folder name to     Header instead of Headder

**Comment by AmshenShanu07** [comment]
1. Cursor pointer on filter button
2. Made filter better by making it bit small and bold
3. Made the filter icon bit small to match with the text size
4. Made border radius only on left top and left bottom
5. Fix the spelling mistake in the title of header
6. Renamed the Headder=>Header
