### ISSUE TITLE
can;t find load more comments button in add book page

### ISSUE THREAD

**Issue by MUHSIN22** [Texki-developers/pickbooks-frontend#43]
![Screenshot from 2021-05-21 16-55-12](https://user-images.githubusercontent.com/70310447/119130103-5ff7e480-ba55-11eb-827d-8ff8a1d37226.png)

in add book page i can't find the load more comments button

one more thing we need some spaces betweee comment section and footer

**Comment by AmshenShanu07** [comment]
done!
